/*
 * layout.c — where each field of a chip sits inside the module's memory.
 *
 * Built to WebAssembly and run, never built natively: a struct's offsets
 * belong to the target that laid it out, and a wasm32 pointer is half the
 * width of the machine that builds this.
 */
#include <stddef.h>
#include <stdio.h>

#include "crtc.h"
#include "drive.h"
#include "floppy.h"
#include "gate_array.h"
#include "upd765.h"
#include "z80.h"

int main(void) {
  printf("/* Generated by emulator/layout.c. Offsets into the module's memory. */\n");

  printf("export const Z80_SIZE = %zu\n", sizeof(z80_t));
  printf("export const Z80_AT_A = %zu\n", offsetof(z80_t, a));
  printf("export const Z80_AT_F = %zu\n", offsetof(z80_t, f));
  printf("export const Z80_AT_B = %zu\n", offsetof(z80_t, b));
  printf("export const Z80_AT_C = %zu\n", offsetof(z80_t, c));
  printf("export const Z80_AT_D = %zu\n", offsetof(z80_t, d));
  printf("export const Z80_AT_E = %zu\n", offsetof(z80_t, e));
  printf("export const Z80_AT_H = %zu\n", offsetof(z80_t, h));
  printf("export const Z80_AT_L = %zu\n", offsetof(z80_t, l));
  printf("export const Z80_AT_AF_ = %zu\n", offsetof(z80_t, af_));
  printf("export const Z80_AT_BC_ = %zu\n", offsetof(z80_t, bc_));
  printf("export const Z80_AT_DE_ = %zu\n", offsetof(z80_t, de_));
  printf("export const Z80_AT_HL_ = %zu\n", offsetof(z80_t, hl_));
  /* The alternate set is stored as whole words, so its halves are addressed
   * through the target's byte order: the low byte of a register first. */
  printf("export const Z80_AT_A_ = %zu\n", offsetof(z80_t, af_) + 1);
  printf("export const Z80_AT_F_ = %zu\n", offsetof(z80_t, af_));
  printf("export const Z80_AT_B_ = %zu\n", offsetof(z80_t, bc_) + 1);
  printf("export const Z80_AT_C_ = %zu\n", offsetof(z80_t, bc_));
  printf("export const Z80_AT_D_ = %zu\n", offsetof(z80_t, de_) + 1);
  printf("export const Z80_AT_E_ = %zu\n", offsetof(z80_t, de_));
  printf("export const Z80_AT_H_ = %zu\n", offsetof(z80_t, hl_) + 1);
  printf("export const Z80_AT_L_ = %zu\n", offsetof(z80_t, hl_));

  printf("export const Z80_AT_IXH = %zu\n", offsetof(z80_t, ixh));
  printf("export const Z80_AT_IXL = %zu\n", offsetof(z80_t, ixl));
  printf("export const Z80_AT_IYH = %zu\n", offsetof(z80_t, iyh));
  printf("export const Z80_AT_IYL = %zu\n", offsetof(z80_t, iyl));
  printf("export const Z80_AT_SP = %zu\n", offsetof(z80_t, sp));
  printf("export const Z80_AT_PC = %zu\n", offsetof(z80_t, pc));
  printf("export const Z80_AT_WZ = %zu\n", offsetof(z80_t, wz));
  printf("export const Z80_AT_I = %zu\n", offsetof(z80_t, i));
  printf("export const Z80_AT_R = %zu\n", offsetof(z80_t, r));
  printf("export const Z80_AT_IM = %zu\n", offsetof(z80_t, im));
  printf("export const Z80_AT_IFF1 = %zu\n", offsetof(z80_t, iff1));
  printf("export const Z80_AT_IFF2 = %zu\n", offsetof(z80_t, iff2));
  printf("export const Z80_AT_HALTED = %zu\n", offsetof(z80_t, halted));
  printf("export const Z80_AT_EI = %zu\n", offsetof(z80_t, ei));
  printf("export const Z80_AT_INTERRUPT_SHADOW = %zu\n", offsetof(z80_t, interrupt_shadow));
  printf("export const Z80_AT_INT_LINE = %zu\n", offsetof(z80_t, int_line));

  printf("export const Z80_FLAG_S = %d\n", Z80_FLAG_S);
  printf("export const Z80_FLAG_Z = %d\n", Z80_FLAG_Z);
  printf("export const Z80_FLAG_Y = %d\n", Z80_FLAG_Y);
  printf("export const Z80_FLAG_H = %d\n", Z80_FLAG_H);
  printf("export const Z80_FLAG_X = %d\n", Z80_FLAG_X);
  printf("export const Z80_FLAG_PV = %d\n", Z80_FLAG_PV);
  printf("export const Z80_FLAG_N = %d\n", Z80_FLAG_N);
  printf("export const Z80_FLAG_C = %d\n", Z80_FLAG_C);

  printf("export const CRTC_SIZE = %zu\n", sizeof(crtc_t));
  printf("export const CRTC_AT_REGISTERS = %zu\n", offsetof(crtc_t, registers));
  printf("export const CRTC_REGISTERS = %zu\n", sizeof(((crtc_t *)0)->registers));
  printf("export const CRTC_AT_C0 = %zu\n", offsetof(crtc_t, c0));
  printf("export const CRTC_AT_C4 = %zu\n", offsetof(crtc_t, c4));
  printf("export const CRTC_AT_C9 = %zu\n", offsetof(crtc_t, c9));
  printf("export const CRTC_AT_VMA_ = %zu\n", offsetof(crtc_t, vma_));

  printf("export const GATE_ARRAY_SIZE = %zu\n", sizeof(gate_array_t));
  printf("export const GATE_ARRAY_AT_INKS = %zu\n", offsetof(gate_array_t, inks));
  printf("export const GATE_ARRAY_INKS = %zu\n", sizeof(((gate_array_t *)0)->inks));
  printf("export const GATE_ARRAY_AT_MODE = %zu\n", offsetof(gate_array_t, mode));
  printf("export const GATE_ARRAY_AT_MODE_PENDING = %zu\n", offsetof(gate_array_t, mode_pending));
  printf("export const GATE_ARRAY_AT_PEN = %zu\n", offsetof(gate_array_t, pen));
  printf("export const GATE_ARRAY_AT_LOWER_ROM = %zu\n", offsetof(gate_array_t, lower_rom_enabled));
  printf("export const GATE_ARRAY_AT_UPPER_ROM = %zu\n", offsetof(gate_array_t, upper_rom_enabled));
  printf("export const GATE_ARRAY_AT_R52 = %zu\n", offsetof(gate_array_t, r52));
  printf("export const GATE_ARRAY_AT_INTERRUPT_REQUEST = %zu\n",
         offsetof(gate_array_t, interrupt_request));

  printf("export const UPD765_SIZE = %zu\n", sizeof(upd765_t));
  printf("export const UPD765_AT_PHASE = %zu\n", offsetof(upd765_t, phase));
  printf("export const UPD765_AT_COMMAND = %zu\n", offsetof(upd765_t, command));
  printf("export const UPD765_AT_COMMAND_RECEIVED = %zu\n", offsetof(upd765_t, command_received));
  printf("export const UPD765_AT_RESULT = %zu\n", offsetof(upd765_t, result));
  printf("export const UPD765_AT_RESULT_LENGTH = %zu\n", offsetof(upd765_t, result_length));
  printf("export const UPD765_AT_TERMINAL_COUNT = %zu\n", offsetof(upd765_t, terminal_count));
  printf("export const UPD765_AT_ST0 = %zu\n", offsetof(upd765_t, st0));
  printf("export const UPD765_AT_ST1 = %zu\n", offsetof(upd765_t, st1));
  printf("export const UPD765_AT_ST2 = %zu\n", offsetof(upd765_t, st2));
  printf("export const UPD765_AT_C = %zu\n", offsetof(upd765_t, c));
  printf("export const UPD765_AT_H = %zu\n", offsetof(upd765_t, h));
  printf("export const UPD765_AT_R = %zu\n", offsetof(upd765_t, r));
  printf("export const UPD765_AT_N = %zu\n", offsetof(upd765_t, n));
  printf("export const UPD765_AT_STEP_TIME = %zu\n", offsetof(upd765_t, step_time));
  printf("export const UPD765_AT_HEAD_UNLOAD_TIME = %zu\n", offsetof(upd765_t, head_unload_time));
  printf("export const UPD765_AT_HEAD_LOAD_TIME = %zu\n", offsetof(upd765_t, head_load_time));
  printf("export const UPD765_AT_NON_DMA = %zu\n", offsetof(upd765_t, non_dma));
  printf("export const UPD765_AT_HEAD_LOADED = %zu\n", offsetof(upd765_t, head_loaded));
  printf("export const UPD765_AT_STAGE = %zu\n", offsetof(upd765_t, stage));
  printf("export const UPD765_AT_TRANSFERRED = %zu\n", offsetof(upd765_t, transferred));
  printf("export const UPD765_AT_TRANSFER_LENGTH = %zu\n", offsetof(upd765_t, transfer_length));
  printf("export const UPD765_COMMAND_BYTES = %d\n", UPD765_COMMAND_BYTES);
  printf("export const UPD765_RESULT_BYTES = %d\n", UPD765_RESULT_BYTES);

  printf("export const UPD765_PHASE_IDLE = %d\n", UPD765_PHASE_IDLE);
  printf("export const UPD765_PHASE_COMMAND = %d\n", UPD765_PHASE_COMMAND);
  printf("export const UPD765_PHASE_EXECUTION = %d\n", UPD765_PHASE_EXECUTION);
  printf("export const UPD765_PHASE_RESULT = %d\n", UPD765_PHASE_RESULT);

  printf("export const UPD765_STAGE_NONE = %d\n", UPD765_STAGE_NONE);
  printf("export const UPD765_STAGE_LOADING_HEAD = %d\n", UPD765_STAGE_LOADING_HEAD);
  printf("export const UPD765_STAGE_FINDING_IDENTITY = %d\n", UPD765_STAGE_FINDING_IDENTITY);
  printf("export const UPD765_STAGE_READING_IDENTITY = %d\n", UPD765_STAGE_READING_IDENTITY);
  printf("export const UPD765_STAGE_TO_DATA = %d\n", UPD765_STAGE_TO_DATA);
  printf("export const UPD765_STAGE_DATA = %d\n", UPD765_STAGE_DATA);
  printf("export const UPD765_STAGE_SKIPPING = %d\n", UPD765_STAGE_SKIPPING);
  printf("export const UPD765_STAGE_CHECK = %d\n", UPD765_STAGE_CHECK);
  printf("export const UPD765_STAGE_WAITING_INDEX = %d\n", UPD765_STAGE_WAITING_INDEX);
  printf("export const UPD765_STAGE_FORMAT_TO_IDENTITY = %d\n", UPD765_STAGE_FORMAT_TO_IDENTITY);
  printf("export const UPD765_STAGE_FORMAT_IDENTITY = %d\n", UPD765_STAGE_FORMAT_IDENTITY);
  printf("export const UPD765_STAGE_FORMAT_FIELD = %d\n", UPD765_STAGE_FORMAT_FIELD);
  printf("export const UPD765_STAGE_FORMAT_ENDING = %d\n", UPD765_STAGE_FORMAT_ENDING);

  printf("export const UPD765_MSR_RQM = %d\n", UPD765_MSR_RQM);
  printf("export const UPD765_MSR_DIO = %d\n", UPD765_MSR_DIO);
  printf("export const UPD765_MSR_EXM = %d\n", UPD765_MSR_EXM);
  printf("export const UPD765_MSR_CB = %d\n", UPD765_MSR_CB);

  printf("export const UPD765_ST0_NORMAL = %d\n", UPD765_ST0_NORMAL);
  printf("export const UPD765_ST0_ABNORMAL = %d\n", UPD765_ST0_ABNORMAL);
  printf("export const UPD765_ST0_INVALID = %d\n", UPD765_ST0_INVALID);
  printf("export const UPD765_ST0_READY_CHANGED = %d\n", UPD765_ST0_READY_CHANGED);
  printf("export const UPD765_ST0_SE = %d\n", UPD765_ST0_SE);
  printf("export const UPD765_ST0_EC = %d\n", UPD765_ST0_EC);
  printf("export const UPD765_ST0_NR = %d\n", UPD765_ST0_NR);
  printf("export const UPD765_ST0_HD = %d\n", UPD765_ST0_HD);
  printf("export const UPD765_ST0_US = %d\n", UPD765_ST0_US);

  printf("export const UPD765_ST1_EN = %d\n", UPD765_ST1_EN);
  printf("export const UPD765_ST1_DE = %d\n", UPD765_ST1_DE);
  printf("export const UPD765_ST1_OR = %d\n", UPD765_ST1_OR);
  printf("export const UPD765_ST1_ND = %d\n", UPD765_ST1_ND);
  printf("export const UPD765_ST1_NW = %d\n", UPD765_ST1_NW);
  printf("export const UPD765_ST1_MA = %d\n", UPD765_ST1_MA);

  printf("export const UPD765_ST2_CM = %d\n", UPD765_ST2_CM);
  printf("export const UPD765_ST2_DD = %d\n", UPD765_ST2_DD);
  printf("export const UPD765_ST2_WC = %d\n", UPD765_ST2_WC);
  printf("export const UPD765_ST2_SH = %d\n", UPD765_ST2_SH);
  printf("export const UPD765_ST2_SN = %d\n", UPD765_ST2_SN);
  printf("export const UPD765_ST2_BC = %d\n", UPD765_ST2_BC);
  printf("export const UPD765_ST2_MD = %d\n", UPD765_ST2_MD);

  printf("export const DRIVE_SIZE = %zu\n", sizeof(drive_t));
  printf("export const DRIVE_AT_FLOPPY = %zu\n", offsetof(drive_t, floppy));
  printf("export const DRIVE_AT_MOTOR = %zu\n", offsetof(drive_t, motor));
  printf("export const DRIVE_AT_SIDE = %zu\n", offsetof(drive_t, side));
  printf("export const DRIVE_AT_CYLINDER = %zu\n", offsetof(drive_t, cylinder));
  printf("export const DRIVE_AT_POSITION = %zu\n", offsetof(drive_t, position));
  printf("export const DRIVE_AT_REVOLUTIONS = %zu\n", offsetof(drive_t, revolutions));
  printf("export const DRIVE_AT_SPIN_UP = %zu\n", offsetof(drive_t, spin_up));

  printf("export const FLOPPY_SIZE = %zu\n", sizeof(floppy_t));
  printf("export const FLOPPY_AT_CYLINDERS = %zu\n", offsetof(floppy_t, cylinders));
  printf("export const FLOPPY_AT_SIDES = %zu\n", offsetof(floppy_t, sides));
  printf("export const FLOPPY_AT_WRITE_PROTECTED = %zu\n", offsetof(floppy_t, write_protected));
  printf("export const FLOPPY_AT_MODIFIED = %zu\n", offsetof(floppy_t, modified));
  printf("export const FLOPPY_AT_TRACKS = %zu\n", offsetof(floppy_t, tracks));
  printf("export const FLOPPY_MAX_CYLINDERS = %d\n", FLOPPY_MAX_CYLINDERS);
  printf("export const FLOPPY_MAX_SIDES = %d\n", FLOPPY_MAX_SIDES);
  printf("export const FLOPPY_BYTES_PER_REVOLUTION = %d\n", FLOPPY_BYTES_PER_REVOLUTION);

  printf("export const FLOPPY_TRACK_SIZE = %zu\n", sizeof(floppy_track_t));
  printf("export const FLOPPY_TRACK_AT_FORMATTED = %zu\n", offsetof(floppy_track_t, formatted));
  printf("export const FLOPPY_TRACK_AT_UNREADABLE = %zu\n", offsetof(floppy_track_t, unreadable));
  printf("export const FLOPPY_TRACK_AT_SECTOR_COUNT = %zu\n",
         offsetof(floppy_track_t, sector_count));
  printf("export const FLOPPY_TRACK_AT_GAP = %zu\n", offsetof(floppy_track_t, gap));
  printf("export const FLOPPY_TRACK_AT_FILLER = %zu\n", offsetof(floppy_track_t, filler));
  printf("export const FLOPPY_TRACK_AT_LENGTH = %zu\n", offsetof(floppy_track_t, length));
  printf("export const FLOPPY_TRACK_AT_SECTORS = %zu\n", offsetof(floppy_track_t, sectors));

  printf("export const FLOPPY_SECTOR_SIZE = %zu\n", sizeof(floppy_sector_t));
  printf("export const FLOPPY_SECTOR_AT_C = %zu\n", offsetof(floppy_sector_t, c));
  printf("export const FLOPPY_SECTOR_AT_H = %zu\n", offsetof(floppy_sector_t, h));
  printf("export const FLOPPY_SECTOR_AT_R = %zu\n", offsetof(floppy_sector_t, r));
  printf("export const FLOPPY_SECTOR_AT_N = %zu\n", offsetof(floppy_sector_t, n));
  printf("export const FLOPPY_SECTOR_AT_DELETED = %zu\n", offsetof(floppy_sector_t, deleted));
  printf("export const FLOPPY_SECTOR_AT_IDENTITY_CRC_ERROR = %zu\n",
         offsetof(floppy_sector_t, identity_crc_error));
  printf("export const FLOPPY_SECTOR_AT_DATA_CRC_ERROR = %zu\n",
         offsetof(floppy_sector_t, data_crc_error));
  printf("export const FLOPPY_SECTOR_AT_NO_DATA_FIELD = %zu\n",
         offsetof(floppy_sector_t, no_data_field));
  printf("export const FLOPPY_SECTOR_AT_ANNOUNCED = %zu\n", offsetof(floppy_sector_t, announced));
  printf("export const FLOPPY_SECTOR_AT_RECORDED = %zu\n", offsetof(floppy_sector_t, recorded));
  printf("export const FLOPPY_SECTOR_AT_EXTENT = %zu\n", offsetof(floppy_sector_t, extent));
  printf("export const FLOPPY_SECTOR_AT_COPIES = %zu\n", offsetof(floppy_sector_t, copies));
  printf("export const FLOPPY_SECTOR_AT_POSITION = %zu\n", offsetof(floppy_sector_t, position));

  return 0;
}
