/*
 * layout.c — where each field of a chip sits inside the module's memory.
 *
 * Built to WebAssembly and run, never built natively: a struct's offsets
 * belong to the target that laid it out, and a wasm32 pointer is half the
 * width of the machine that builds this.
 */
#include <stddef.h>
#include <stdio.h>

#include "crtc.h"
#include "z80.h"

int main(void) {
  printf("/* Generated by emulator/layout.c. Offsets into the module's memory. */\n");

  printf("export const Z80_SIZE = %zu\n", sizeof(z80_t));
  printf("export const Z80_AT_PC = %zu\n", offsetof(z80_t, pc));

  printf("export const CRTC_SIZE = %zu\n", sizeof(crtc_t));
  printf("export const CRTC_AT_REGISTERS = %zu\n", offsetof(crtc_t, registers));
  printf("export const CRTC_REGISTERS = %zu\n", sizeof(((crtc_t *)0)->registers));
  printf("export const CRTC_AT_C0 = %zu\n", offsetof(crtc_t, c0));
  printf("export const CRTC_AT_C4 = %zu\n", offsetof(crtc_t, c4));
  printf("export const CRTC_AT_C9 = %zu\n", offsetof(crtc_t, c9));

  return 0;
}
