/*
 * layout.c — where each field of a chip sits inside the module's memory.
 *
 * Built to WebAssembly and run, never built natively: a struct's offsets
 * belong to the target that laid it out, and a wasm32 pointer is half the
 * width of the machine that builds this.
 */
#include <stddef.h>
#include <stdio.h>

#include "crtc.h"
#include "gate_array.h"
#include "z80.h"

int main(void) {
  printf("/* Generated by emulator/layout.c. Offsets into the module's memory. */\n");

  printf("export const Z80_SIZE = %zu\n", sizeof(z80_t));
  printf("export const Z80_AT_A = %zu\n", offsetof(z80_t, a));
  printf("export const Z80_AT_F = %zu\n", offsetof(z80_t, f));
  printf("export const Z80_AT_B = %zu\n", offsetof(z80_t, b));
  printf("export const Z80_AT_C = %zu\n", offsetof(z80_t, c));
  printf("export const Z80_AT_D = %zu\n", offsetof(z80_t, d));
  printf("export const Z80_AT_E = %zu\n", offsetof(z80_t, e));
  printf("export const Z80_AT_H = %zu\n", offsetof(z80_t, h));
  printf("export const Z80_AT_L = %zu\n", offsetof(z80_t, l));
  printf("export const Z80_AT_AF_ = %zu\n", offsetof(z80_t, af_));
  printf("export const Z80_AT_BC_ = %zu\n", offsetof(z80_t, bc_));
  printf("export const Z80_AT_DE_ = %zu\n", offsetof(z80_t, de_));
  printf("export const Z80_AT_HL_ = %zu\n", offsetof(z80_t, hl_));
  /* The alternate set is stored as whole words, so its halves are addressed
   * through the target's byte order: the low byte of a register first. */
  printf("export const Z80_AT_A_ = %zu\n", offsetof(z80_t, af_) + 1);
  printf("export const Z80_AT_F_ = %zu\n", offsetof(z80_t, af_));
  printf("export const Z80_AT_B_ = %zu\n", offsetof(z80_t, bc_) + 1);
  printf("export const Z80_AT_C_ = %zu\n", offsetof(z80_t, bc_));
  printf("export const Z80_AT_D_ = %zu\n", offsetof(z80_t, de_) + 1);
  printf("export const Z80_AT_E_ = %zu\n", offsetof(z80_t, de_));
  printf("export const Z80_AT_H_ = %zu\n", offsetof(z80_t, hl_) + 1);
  printf("export const Z80_AT_L_ = %zu\n", offsetof(z80_t, hl_));

  printf("export const Z80_AT_IXH = %zu\n", offsetof(z80_t, ixh));
  printf("export const Z80_AT_IXL = %zu\n", offsetof(z80_t, ixl));
  printf("export const Z80_AT_IYH = %zu\n", offsetof(z80_t, iyh));
  printf("export const Z80_AT_IYL = %zu\n", offsetof(z80_t, iyl));
  printf("export const Z80_AT_SP = %zu\n", offsetof(z80_t, sp));
  printf("export const Z80_AT_PC = %zu\n", offsetof(z80_t, pc));
  printf("export const Z80_AT_WZ = %zu\n", offsetof(z80_t, wz));
  printf("export const Z80_AT_I = %zu\n", offsetof(z80_t, i));
  printf("export const Z80_AT_R = %zu\n", offsetof(z80_t, r));
  printf("export const Z80_AT_IM = %zu\n", offsetof(z80_t, im));
  printf("export const Z80_AT_IFF1 = %zu\n", offsetof(z80_t, iff1));
  printf("export const Z80_AT_IFF2 = %zu\n", offsetof(z80_t, iff2));
  printf("export const Z80_AT_HALTED = %zu\n", offsetof(z80_t, halted));
  printf("export const Z80_AT_EI = %zu\n", offsetof(z80_t, ei));
  printf("export const Z80_AT_INTERRUPT_SHADOW = %zu\n", offsetof(z80_t, interrupt_shadow));
  printf("export const Z80_AT_INT_LINE = %zu\n", offsetof(z80_t, int_line));

  printf("export const Z80_FLAG_S = %d\n", Z80_FLAG_S);
  printf("export const Z80_FLAG_Z = %d\n", Z80_FLAG_Z);
  printf("export const Z80_FLAG_Y = %d\n", Z80_FLAG_Y);
  printf("export const Z80_FLAG_H = %d\n", Z80_FLAG_H);
  printf("export const Z80_FLAG_X = %d\n", Z80_FLAG_X);
  printf("export const Z80_FLAG_PV = %d\n", Z80_FLAG_PV);
  printf("export const Z80_FLAG_N = %d\n", Z80_FLAG_N);
  printf("export const Z80_FLAG_C = %d\n", Z80_FLAG_C);

  printf("export const CRTC_SIZE = %zu\n", sizeof(crtc_t));
  printf("export const CRTC_AT_REGISTERS = %zu\n", offsetof(crtc_t, registers));
  printf("export const CRTC_REGISTERS = %zu\n", sizeof(((crtc_t *)0)->registers));
  printf("export const CRTC_AT_C0 = %zu\n", offsetof(crtc_t, c0));
  printf("export const CRTC_AT_C4 = %zu\n", offsetof(crtc_t, c4));
  printf("export const CRTC_AT_C9 = %zu\n", offsetof(crtc_t, c9));
  printf("export const CRTC_AT_VMA_ = %zu\n", offsetof(crtc_t, vma_));

  printf("export const GATE_ARRAY_SIZE = %zu\n", sizeof(gate_array_t));
  printf("export const GATE_ARRAY_AT_INKS = %zu\n", offsetof(gate_array_t, inks));
  printf("export const GATE_ARRAY_INKS = %zu\n", sizeof(((gate_array_t *)0)->inks));
  printf("export const GATE_ARRAY_AT_MODE = %zu\n", offsetof(gate_array_t, mode));

  return 0;
}
